language: python
python:
  - "3.6"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls --quiet


# command to run tests
script: 
nose2
after_success: coveralls
